/**
 * masterdb2/db/import-packet.js — v2 packet import (preview + commit)
 *
 * Two-phase design:
 *   previewImport(packet)
 *     Read-only analysis. Returns proposed location, per-worker match type and score,
 *     duplicate/baseline flags, and a summary count. The import screen renders this
 *     and collects any decisions the user must make.
 *
 *   commitImport(packet, decisions, writerName, { techFolder, filename })
 *     Executes the import: pre-import snapshot → atomic transaction → db.save → archive.
 *     Throws on any reconciliation mismatch — the whole packet rolls back.
 *
 * V2 changes from the legacy import:
 *   - No auto-create company or location — unknown location blocks the import
 *   - Person-level matching: uid-first (schema 1.1), then employee_id, then
 *     multi-identifier scoring via workers.matchCandidates()
 *   - First test is a baseline at PERSON level (not location level)
 *   - Pre-import snapshot mandatory; backup_log row written inside the transaction
 *   - reconcileImport (shared/validation) is the final fail-loud gate before COMMIT
 */

import { query, scalar, run, transaction, snapshotForImport, archivePacket, save, listInbox, readPacket } from './db.js'
import { getById, getByUid, getActiveBaseline, create as createPerson, matchCandidates } from './workers.js'
import { classify }                     from '../../shared/classification/engine.js'
import { validatePacket }               from '../../shared/packet/schema.js'
import { reconcileImport, countPacketCompletedTests } from '../../shared/validation/reconcile-import.js'

// ── Constants ─────────────────────────────────────────────────────────────────

const THR = [
  'left_500','left_1k','left_2k','left_3k','left_4k','left_6k','left_8k',
  'right_500','right_1k','right_2k','right_3k','right_4k','right_6k','right_8k'
]

const TEST_COLS = [
  'employee_id','location_id','test_date','tech_id','test_type','province',
  ...THR,
  'classification','triggered_rule_id','sts_flag','counsel_text','tech_notes',
  'questionnaire','packet_id','referral_given_to_worker',
  'triggering_freq_hz','triggering_ear','shift_db'
]

// ── Private helpers ───────────────────────────────────────────────────────────

const queryOne  = (sql, p = []) => query(sql, p)[0] ?? null
const hasData   = th => THR.some(k => th?.[k] != null && th[k] !== '')

function resolveCompany(packet) {
  const id   = packet.company?.company_id
  const name = packet.company?.name
  if (id != null) {
    const row = queryOne('SELECT * FROM companies WHERE company_id = ? AND active = 1', [id])
    if (row) return row
  }
  if (name) {
    return queryOne('SELECT * FROM companies WHERE LOWER(name) = LOWER(?) AND active = 1', [name])
  }
  return null
}

function resolveLocation(packet, company, locationIdOverride = null) {
  if (locationIdOverride != null) {
    return queryOne('SELECT * FROM locations WHERE location_id = ? AND active = 1', [locationIdOverride])
  }
  const loc = packet.location
  if (!loc) return null
  if (loc.location_id != null) {
    const row = queryOne(
      'SELECT * FROM locations WHERE location_id = ? AND company_id = ? AND active = 1',
      [loc.location_id, company.company_id]
    )
    if (row) return row
  }
  if (loc.location_uid) {
    const row = queryOne('SELECT * FROM locations WHERE uid = ? AND active = 1', [loc.location_uid])
    if (row) return row
  }
  if (loc.name && company) {
    return queryOne(
      'SELECT * FROM locations WHERE company_id = ? AND LOWER(name) = LOWER(?) AND active = 1',
      [company.company_id, loc.name]
    )
  }
  return null
}

// Determine match type and confidence for one packet employee.
// Returns { type, employee|null, score|null, reason|null, candidates, needsConfirmation }
function matchEmployee(packetEmp, companyId) {
  // 1. uid-first (schema 1.1 roster workers carry uid)
  if (packetEmp.uid) {
    const emp = getByUid(packetEmp.uid)
    if (emp) return { type: 'exact_uid', employee: emp, score: null, reason: null, candidates: [], needsConfirmation: false }
  }
  // 2. employee_id exact match (numeric = generated by MasterDB, not a temp 'new_xxx' id)
  const idNum = Number(packetEmp.employee_id)
  if (!isNaN(idNum) && idNum > 0) {
    const emp = getById(idNum)
    if (emp) return { type: 'exact_id', employee: emp, score: null, reason: null, candidates: [], needsConfirmation: false }
  }
  // 3. on-site-added worker (no uid, no numeric id) — score against company
  const candidates = matchCandidates(
    { first_name: packetEmp.first_name, last_name: packetEmp.last_name,
      dob: packetEmp.dob, sin_last_4: packetEmp.sin_last_4 },
    companyId
  )
  if (!candidates.length) {
    return { type: 'new', employee: null, score: null, reason: null, candidates: [], needsConfirmation: false }
  }
  const top = candidates[0]
  if (top.score >= 3) {
    return { type: 'strong', employee: top.employee, score: top.score, reason: top.reason, candidates, needsConfirmation: false }
  }
  return { type: 'weak', employee: top.employee, score: top.score, reason: top.reason, candidates, needsConfirmation: true }
}

function isDuplicateTest(employeeId, test, techId) {
  return !!queryOne(
    'SELECT 1 FROM tests WHERE employee_id = ? AND test_date = ? AND tech_id = ? AND deleted_at IS NULL',
    [employeeId, test.test_date, test.tech_id ?? techId ?? null]
  )
}

function insertTest(fields) {
  run(
    `INSERT INTO tests (${TEST_COLS.join(',')}) VALUES (${TEST_COLS.map(() => '?').join(',')})`,
    TEST_COLS.map(c => fields[c] ?? null)
  )
  return scalar('SELECT last_insert_rowid()')
}

function insertHpdAssessment(testId, hpd) {
  if (!hpd) return
  run(
    `INSERT INTO hpd_assessments (test_id, hpd_make_model, rated_nrr, derated_nrr, lex8hr, protected_exposure, adequacy)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [testId, hpd.hpd_make_model ?? null, hpd.rated_nrr ?? null, hpd.derated_nrr ?? null,
     hpd.lex8hr ?? null, hpd.protected_exposure ?? null, hpd.adequacy ?? null]
  )
}

function insertBaseline(employeeId, locationId, testDate, thresholds) {
  // Archive any existing active baseline first (shouldn't exist by this point, but be safe)
  run(`UPDATE baselines SET archived = 1 WHERE employee_id = ? AND archived = 0`, [employeeId])
  run(
    `INSERT INTO baselines (employee_id, location_id, test_date, archived, ${THR.join(',')})
     VALUES (?, ?, ?, 0, ${THR.map(() => '?').join(',')})`,
    [employeeId, locationId, testDate, ...THR.map(k => thresholds?.[k] ?? null)]
  )
}

// ── Phase 1: preview (synchronous, no writes) ─────────────────────────────────

/**
 * Analyse a packet and return a preview for the import screen to render.
 *
 * Returns:
 *   { packetId, visitDate, company, location, employees, counts, warnings }
 *
 * employees[] entries:
 *   { packetEmp, match, completedTests: [{ test, isDuplicate, wouldBaseline }], warnings }
 *
 * match.type values:
 *   'exact_uid'  — schema 1.1 uid hit (strongest, never needs confirmation)
 *   'exact_id'   — employee_id hit
 *   'strong'     — score >= 3 (name + DOB, auto-proposed)
 *   'weak'       — score < 3 (needsConfirmation: true — import screen must collect decision)
 *   'new'        — no candidates, will create a new person
 *
 * counts.unconfirmed > 0 or location.status === 'unknown' means commit will
 * require decisions before it can run.
 */
export function previewImport(packet) {
  const structCheck = validatePacket(packet)
  if (!structCheck.valid) throw new Error(`Invalid packet: ${structCheck.errors.join('; ')}`)

  const warnings  = []
  const province  = packet.company?.province ?? packet.visit?.province ?? 'BC'
  const techId    = packet.tech?.tech_id ?? null

  // Company
  const company = resolveCompany(packet)
  if (!company) warnings.push(`Company "${packet.company?.name}" not found in DB — location resolution will fail`)

  // Location
  const locRow = company ? resolveLocation(packet, company) : null
  const location = {
    status: locRow ? 'resolved' : 'unknown',
    row:    locRow,
    packetLocationId:   packet.location?.location_id   ?? null,
    packetLocationName: packet.location?.name          ?? null,
    packetLocationUid:  packet.location?.location_uid  ?? null,
  }
  if (location.status === 'unknown') {
    warnings.push(`Location "${packet.location?.name ?? '?'}" could not be resolved — provide a locationId in decisions before committing`)
  }

  // Rules for re-classification at import
  const rules = (Array.isArray(packet.rules) && packet.rules.length)
    ? packet.rules
    : query('SELECT * FROM classification_rules WHERE province_code = ? ORDER BY priority DESC', [province])
  if (!rules.length) warnings.push(`No classification rules found for ${province} — tests will import as unclassified`)

  // Per-employee analysis
  const employees = []
  let toImport = 0, duplicates = 0, emptyTests = 0, newPersons = 0, unconfirmed = 0

  for (const packetEmp of packet.employees ?? []) {
    const withTests = (packetEmp.completed_tests ?? []).filter(t => t) // keep all; flag empties below
    if (!withTests.length) continue

    const match   = matchEmployee(packetEmp, company?.company_id ?? null)
    const empWarn = []

    if (match.needsConfirmation) unconfirmed++
    if (match.type === 'new') newPersons++

    // Per-test analysis (only reliable when employee is identified)
    const completedTests = withTests.map(test => {
      const th = test.thresholds ?? {}
      if (!hasData(th)) { emptyTests++; return { test, isEmpty: true, isDuplicate: false, wouldBaseline: false } }

      let isDup      = false
      let wouldBl    = false

      if (match.employee && !match.needsConfirmation) {
        isDup   = isDuplicateTest(match.employee.employee_id, test, techId)
        wouldBl = !isDup && !getActiveBaseline(match.employee.employee_id)
      } else if (match.type === 'new') {
        // New person has no prior tests — first completed test will become baseline
        wouldBl = !isDup && completedTests?.filter(t => !t?.isEmpty).indexOf(test) === 0  // only first
      }

      if (!isDup && match.employee && !match.needsConfirmation) toImport++
      if (isDup) duplicates++
      return { test, isEmpty: false, isDuplicate: isDup, wouldBaseline: wouldBl }
    })

    // For new persons: first non-empty, non-dup test would baseline (set correctly above)
    if (match.type === 'new') {
      let foundFirst = false
      for (const ct of completedTests) {
        if (!ct.isEmpty && !ct.isDuplicate) {
          ct.wouldBaseline = !foundFirst
          if (!foundFirst) { foundFirst = true; toImport++ }
          else toImport++
        }
      }
    }

    if (match.type === 'weak' || match.type === 'strong') {
      empWarn.push(`${match.candidates.length} candidate(s) found — best: ${match.reason}`)
    }

    employees.push({ packetEmp, match, completedTests, warnings: empWarn })
  }

  return {
    packetId: packet.packet_id,
    visitDate: packet.visit?.visit_date ?? null,
    company: { id: company?.company_id, name: company?.name ?? packet.company?.name },
    location,
    employees,
    counts: { toImport, duplicates, empty: emptyTests, newPersons, unconfirmed },
    warnings,
  }
}

// ── Phase 2: commit (async, writes DB then disk) ──────────────────────────────

/**
 * Execute a confirmed import.
 *
 * decisions: {
 *   locationId?: number           — required when preview.location.status === 'unknown'
 *   employees?: {
 *     [packetEmployeeId: string]: { action: 'use_existing', employeeId: number }
 *                               | { action: 'create_new' }
 *   }
 * }
 *
 * techFolder: the tech's OneDrive folder name (for archiving after import)
 * filename:   the packet filename in inbox/ (for archiving after import)
 *
 * Returns { imported, duplicates, empty, newPersons, backupFile }
 * Throws if reconciliation fails — the transaction is rolled back, no disk write occurs.
 */
export async function commitImport(packet, decisions = {}, writerName, { techFolder, filename }) {
  const structCheck = validatePacket(packet)
  if (!structCheck.valid) throw new Error(`Invalid packet: ${structCheck.errors.join('; ')}`)

  const province = packet.company?.province ?? packet.visit?.province ?? 'BC'
  const techId   = packet.tech?.tech_id ?? null

  const company = resolveCompany(packet)
  if (!company) throw new Error(`Company "${packet.company?.name}" not found — cannot import`)

  const resolvedLocation = resolveLocation(packet, company, decisions.locationId ?? null)
  if (!resolvedLocation) throw new Error(`Location could not be resolved. Provide decisions.locationId.`)

  const rules = (Array.isArray(packet.rules) && packet.rules.length)
    ? packet.rules
    : query('SELECT * FROM classification_rules WHERE province_code = ? ORDER BY priority DESC', [province])

  // Mandatory pre-import snapshot (must succeed before any writes)
  const backupFile = await snapshotForImport(packet.packet_id)

  // Atomic import
  let imported = 0, emptyTests = 0, duplicates = 0, newPersons = 0
  const insertedTestIds = []
  const empDecisions = decisions.employees ?? {}

  await transaction(async () => {
    for (const packetEmp of packet.employees ?? []) {
      const withTests = (packetEmp.completed_tests ?? []).filter(t => t)
      if (!withTests.length) continue

      // Resolve employee_id for this import
      const decisionKey = String(packetEmp.employee_id)
      const decision    = empDecisions[decisionKey]

      let employeeId
      if (decision?.action === 'use_existing') {
        // Staff confirmed a specific match (or auto-proposal accepted by default)
        const emp = getById(decision.employeeId)
        if (!emp) throw new Error(`Decision references employee ${decision.employeeId} which does not exist`)
        employeeId = emp.employee_id
      } else if (decision?.action === 'create_new') {
        employeeId = createPerson({
          first_name:          packetEmp.first_name,
          last_name:           packetEmp.last_name,
          middle_name:         packetEmp.middle_name   ?? null,
          dob:                 packetEmp.dob            ?? null,
          sin_last_4:          packetEmp.sin_last_4     ?? null,
          phone:               packetEmp.phone           ?? null,
          email:               packetEmp.email           ?? null,
          hire_date:           packetEmp.hire_date       ?? null,
          job_title:           packetEmp.job_title       ?? null,
          current_location_id: resolvedLocation.location_id,
          status: 'active',
        })
        newPersons++
      } else {
        // No explicit decision — attempt the same auto-resolution as preview
        const match = matchEmployee(packetEmp, company.company_id)
        if (match.needsConfirmation) {
          throw new Error(
            `Employee "${packetEmp.last_name}, ${packetEmp.first_name}" requires a match decision ` +
            `(match type: ${match.type}, score: ${match.score}). Provide decisions.employees["${decisionKey}"].`
          )
        }
        if (match.type === 'new') {
          employeeId = createPerson({
            first_name: packetEmp.first_name, last_name: packetEmp.last_name,
            middle_name: packetEmp.middle_name ?? null, dob: packetEmp.dob ?? null,
            sin_last_4: packetEmp.sin_last_4 ?? null, phone: packetEmp.phone ?? null,
            email: packetEmp.email ?? null, hire_date: packetEmp.hire_date ?? null,
            job_title: packetEmp.job_title ?? null,
            current_location_id: resolvedLocation.location_id, status: 'active',
          })
          newPersons++
        } else {
          employeeId = match.employee.employee_id
        }
      }

      for (const test of withTests) {
        const th = test.thresholds ?? {}
        if (!hasData(th)) { emptyTests++; continue }
        if (isDuplicateTest(employeeId, test, techId)) { duplicates++; continue }

        // Classify against the person's active baseline (person-level, not location-level)
        const baseline = getActiveBaseline(employeeId)
        const cl       = rules.length
          ? classify(th, baseline, rules)
          : { category: null, triggered_rule_id: null, sts_calculated: false,
              sts_value: null, triggering_freq_hz: null, triggering_ear: null, shift_db: null }

        const testId = insertTest({
          employee_id:              employeeId,
          location_id:              resolvedLocation.location_id,
          test_date:                test.test_date,
          tech_id:                  test.tech_id ?? techId,
          test_type:                baseline ? (test.test_type ?? 'Periodic') : 'Baseline',
          province,
          ...th,
          classification:           cl.category,
          triggered_rule_id:        cl.triggered_rule_id,
          sts_flag:                 cl.sts_calculated ? 1 : 0,
          counsel_text:             test.counsel_text ?? null,
          tech_notes:               test.notes        ?? null,   // packet field is 'notes'
          questionnaire:            test.questionnaire ?? null,
          packet_id:                packet.packet_id,
          referral_given_to_worker: test.referral_given_to_worker ? 1 : 0,
          triggering_freq_hz:       cl.triggering_freq_hz,
          triggering_ear:           cl.triggering_ear,
          shift_db:                 cl.shift_db,
        })

        if (test.hpd_assessment?.valid || test.hpd_assessment?.hpd_make_model) {
          insertHpdAssessment(testId, test.hpd_assessment)
        }

        if (!baseline) {
          insertBaseline(employeeId, resolvedLocation.location_id, test.test_date, th)
        }

        insertedTestIds.push(testId)
        imported++
      }
    }

    // Mark packet as imported in the packets table
    run(
      `INSERT OR REPLACE INTO packets
         (packet_id, company_id, location_id, tech_id, visit_date, filename, status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, 'imported', datetime('now'), datetime('now'))`,
      [packet.packet_id, company.company_id, resolvedLocation.location_id,
       techId, packet.visit?.visit_date ?? null, filename ?? packet.filename ?? null]
    )

    // Record the pre-import snapshot inside the same transaction
    run(
      `INSERT INTO backup_log (filename, reason) VALUES (?, ?)`,
      [backupFile, `pre-import:${packet.packet_id}`]
    )

    // Fail-loud gate — throws on any mismatch, rolls back the whole packet
    reconcileImport({
      packet,
      queryOne,
      defaultLocation:    resolvedLocation,
      locationIdOverride: decisions.locationId ?? null,
      imported,
      skippedDuplicate:   duplicates,
      skippedEmpty:       emptyTests,
      insertedTestIds,
    })
  })

  // Only reached if transaction committed cleanly — persist to disk before archiving
  await save(writerName)
  await archivePacket(techFolder, filename)

  return { imported, duplicates, empty: emptyTests, newPersons, backupFile }
}

// ── Auto-import ───────────────────────────────────────────────────────────────

/**
 * Import all "clean" packets from all active techs with a folder configured.
 * A packet is clean when: company resolves, location resolves, and no worker
 * needs manual confirmation (all matches are exact_uid, exact_id, strong, or new).
 *
 * Ambiguous packets (weak match, unknown location, unknown company) are left in
 * the inbox untouched and returned as skipped entries for the LC to review.
 *
 * techs:      array of tech rows from the DB ({ tech_id, name, folder_name })
 * writerName: passed through to save() for the concurrency counter
 *
 * Returns { results: [{ tech, filename, ok, imported?, duplicates?, skipped?, reason? }] }
 */
export async function autoImportClean(techs, writerName) {
  const results = []

  for (const tech of techs) {
    let files = []
    try { files = await listInbox(tech.folder_name) } catch { continue }

    const jsons = files.filter(f => f.kind === 'file' && f.name.endsWith('.json'))

    for (const f of jsons) {
      let packet
      try { packet = await readPacket(tech.folder_name, f.name) } catch (e) {
        results.push({ tech: tech.name, filename: f.name, ok: false, reason: `Read failed: ${e?.message || e}` })
        continue
      }

      let preview
      try { preview = previewImport(packet) } catch (e) {
        results.push({ tech: tech.name, filename: f.name, ok: false, reason: `Preview failed: ${e?.message || e}` })
        continue
      }

      // Skip if anything needs LC judgment
      if (!preview.company.id) {
        results.push({ tech: tech.name, filename: f.name, skipped: true, reason: `Company not found: ${preview.company.name}` })
        continue
      }
      if (preview.location.status !== 'resolved') {
        results.push({ tech: tech.name, filename: f.name, skipped: true, reason: `Location not resolved: ${preview.location.packetLocationName ?? '?'}` })
        continue
      }
      if (preview.counts.unconfirmed > 0) {
        results.push({ tech: tech.name, filename: f.name, skipped: true, reason: `${preview.counts.unconfirmed} worker(s) need manual match confirmation` })
        continue
      }

      // Build decisions from preview auto-proposals
      const employees = {}
      for (const { packetEmp, match } of preview.employees) {
        const key = String(packetEmp.employee_id)
        if (match.type === 'new') {
          employees[key] = { action: 'create_new' }
        } else if (match.employee) {
          employees[key] = { action: 'use_existing', employeeId: match.employee.employee_id }
        }
      }

      try {
        const r = await commitImport(packet, { employees }, writerName, {
          techFolder: tech.folder_name,
          filename:   f.name,
        })
        results.push({ tech: tech.name, filename: f.name, ok: true, ...r })
      } catch (e) {
        results.push({ tech: tech.name, filename: f.name, ok: false, reason: e?.message || e?.toString() || 'Unknown error' })
      }
    }
  }

  return { results }
}
