import { query, queryOne, run, transaction } from '../db/sqlite.js'
import { JsonDatabase } from '../shared/fs/json-database.js'
import { createTest } from '../db/tests.js'
import { createBaseline } from '../db/employees.js'

export function renderDataTools(container, state, navigate) {
  const locations = query(`
    SELECT l.location_id, l.name as loc_name, c.name as co_name 
    FROM locations l 
    JOIN companies c ON l.company_id = c.company_id 
    WHERE l.active = 1
    ORDER BY c.name, l.name
  `);

  container.innerHTML = `
    <div class="page">
      <div class="page-header">
        <h1>Data Management Tools</h1>
      </div>

      <div class="settings-sections">
        
        <!-- SECTION 1: BULK MOVE -->
        <section class="form-card">
          <h2>Bulk Move Employees</h2>
          <p class="help-text">Move employees and history from one location to another.</p>
          <div class="form-grid">
            <div class="form-group">
              <label>Source (FROM)</label>
              <select id="move-from" class="search-input">
                <option value="">-- Select Source --</option>
                ${locations.map(l => `<option value="${l.location_id}">${l.co_name} › ${l.loc_name}</option>`).join('')}
              </select>
            </div>
            <div class="form-group">
              <label>Destination (TO)</label>
              <select id="move-to" class="search-input">
                <option value="">-- Select Destination --</option>
                ${locations.map(l => `<option value="${l.location_id}">${l.co_name} › ${l.loc_name}</option>`).join('')}
              </select>
            </div>
          </div>
          <button class="btn btn-primary btn-sm" id="btn-execute-move" style="margin-top:15px; background:#d9534f;">Execute Move</button>
        </section>

        <!-- SECTION 2: EMBEDDED LEGACY IMPORTER -->
        <section class="form-card" id="legacy-import-section">
          <h2>Legacy CSV Import</h2>
          <p class="help-text">Drop a <code>MASTER_IMPORT_CLEAN.csv</code> generated by the Surgical Macro.</p>
          
          <div class="drop-zone" id="drop-zone" style="border: 2px dashed #ccc; padding: 30px; text-align: center; border-radius: 8px; cursor: pointer;">
            <div style="font-size: 30px; margin-bottom: 10px;">📄</div>
            <strong>Click or Drop CSV file here</strong>
            <input type="file" id="file-picker" accept=".csv" style="display:none" />
          </div>

          <div id="import-preview-area" class="hidden" style="margin-top:20px;">
            <div id="preview-stats" style="font-weight:bold; margin-bottom:10px;"></div>
            <div style="max-height: 300px; overflow: auto; border: 1px solid #eee; margin-bottom: 15px;">
                <table class="data-table" style="font-size:11px;">
                    <thead style="position:sticky; top:0; background:#eee;">
                        <tr><th>Company</th><th>Location</th><th>Employee</th><th>Date</th></tr>
                    </thead>
                    <tbody id="preview-tbody"></tbody>
                </table>
            </div>
            <div style="display:flex; gap:10px; justify-content: flex-end;">
                <button class="btn btn-ghost btn-sm" id="btn-cancel-import">Cancel</button>
                <button class="btn btn-primary btn-sm" id="btn-run-import">Confirm & Import All</button>
            </div>
          </div>
        </section>

      </div>
    </div>
  `;

  // --- LOGIC: BULK MOVE ---
  container.querySelector('#btn-execute-move').onclick = () => {
    const fromId = container.querySelector('#move-from').value;
    const toId = container.querySelector('#move-to').value;
    if (!fromId || !toId || fromId === toId) return alert("Select different source and destination.");

    if (confirm("Move all employees and test history permanently?")) {
      transaction(({ run }) => {
        run("UPDATE employees SET location_id = ? WHERE location_id = ?", [toId, fromId]);
        run("UPDATE tests SET location_id = ? WHERE location_id = ?", [toId, fromId]);
        run("UPDATE baselines SET location_id = ? WHERE location_id = ?", [toId, fromId]);
      });
      alert("Move complete. Syncing to OneDrive...");
      JsonDatabase.pushMaster(state.syncFolder, query);
      navigate('dashboard');
    }
  };

  // --- LOGIC: EMBEDDED IMPORTER ---
  const dropZone = container.querySelector('#drop-zone');
  const filePicker = container.querySelector('#file-picker');
  const previewArea = container.querySelector('#import-preview-area');
  let parsedRows = [];

  dropZone.onclick = () => filePicker.click();
  filePicker.onchange = (e) => handleFile(e.target.files[0]);

  async function handleFile(file) {
    if (!file) return;
    const text = await file.text();
    parsedRows = parseSurgicalCSV(text);
    
    container.querySelector('#preview-stats').textContent = `Detected ${parsedRows.length} records in file.`;
    container.querySelector('#preview-tbody').innerHTML = parsedRows.slice(0, 50).map(r => `
        <tr>
            <td style="color:blue">${esc(r.rowCompany)}</td>
            <td>${esc(r.rowLocation)}</td>
            <td>${esc(r.lastName)}, ${esc(r.firstName)}</td>
            <td>${esc(r.testDate)}</td>
        </tr>
    `).join('');
    
    dropZone.classList.add('hidden');
    previewArea.classList.remove('hidden');
  }

  container.querySelector('#btn-run-import').onclick = async () => {
    const btn = container.querySelector('#btn-run-import');
    btn.disabled = true;
    btn.textContent = "Importing...";

    try {
        transaction(() => {
            for (const row of parsedRows) {
                // 1. Resolve Company/Location IDs (Same logic as we built before)
                let co = queryOne("SELECT company_id FROM companies WHERE name = ? COLLATE NOCASE", [row.rowCompany]);
                if (!co) {
                    run("INSERT INTO companies (name, active) VALUES (?, 1)", [row.rowCompany]);
                    co = { company_id: queryOne("SELECT last_insert_rowid() as id").id };
                }
                
                let loc = queryOne("SELECT location_id FROM locations WHERE company_id = ? AND name = ? COLLATE NOCASE", [co.company_id, row.rowLocation]);
                if (!loc) {
                    run("INSERT INTO locations (company_id, name, province, active) VALUES (?, ?, ?, 1)", [co.company_id, row.rowLocation, row.province]);
                    loc = { location_id: queryOne("SELECT last_insert_rowid() as id").id };
                }

                // 2. Resolve Employee
                let emp = queryOne("SELECT employee_id FROM employees WHERE location_id = ? AND first_name = ? AND last_name = ?", [loc.location_id, row.firstName, row.lastName]);
                if (!emp) {
                    run("INSERT INTO employees (location_id, first_name, last_name, dob, job_title, status) VALUES (?, ?, ?, ?, ?, 'active')", 
                        [loc.location_id, row.firstName, row.lastName, row.dob, row.occupation]);
                    emp = { employee_id: queryOne("SELECT last_insert_rowid() as id").id };
                }

                // 3. Create Test
                createTest({ ...row, employee_id: emp.employee_id, location_id: loc.location_id });

                // 4. NEW: Auto-Baseline Logic
                // If this is the ONLY test for this person, make it a baseline too
                const count = queryOne("SELECT COUNT(*) as n FROM tests WHERE employee_id = ?", [emp.employee_id]).n;
                if (count === 1) {
                    createBaseline(emp.employee_id, loc.location_id, row.testDate, row);
                }
            }
        });

        alert("Import successful!");
        if (state.syncFolder) await JsonDatabase.pushMaster(state.syncFolder, query);
        navigate('dashboard');
    } catch (e) {
        alert("Import failed: " + e.message);
        btn.disabled = false;
    }
  };

  container.querySelector('#btn-cancel-import').onclick = () => navigate('data-tools');
}

// --- RE-USE OUR ROBUST PARSER ---
function parseSurgicalCSV(csvText) {
  const lines = csvText.split(/\r?\n/);
  const allRows = [];
  let curCo = "", curLoc = "", curProv = "AB", parsing = false;
  
  const splitSafe = (l) => {
    const res = []; let c = "", q = false;
    for (let char of l) {
      if (char === '"') q = !q;
      else if (char === ',' && !q) { res.push(c.trim()); c = ""; }
      else c += char;
    }
    res.push(c.trim()); return res;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    if (line.includes("### RECORD ###")) {
        const meta = splitSafe(lines[i+2] || "");
        curCo = meta[0]?.replace(/^"|"$/g, '') || "Unknown";
        curLoc = meta[1]?.replace(/^"|"$/g, '') || "Main Office";
        curProv = meta[2] || "AB";
        i += 2; parsing = false; continue;
    }
    if (line.toLowerCase().startsWith("first name")) { parsing = true; continue; }
    if (parsing) {
        const r = splitSafe(line);
        if (r.length < 5 || r[0].includes("MMDDYYYY")) continue;
        const testDate = parseDate(r[4]);
        if (testDate) {
            allRows.push({
                firstName: r[0], lastName: r[1], occupation: r[2], dob: parseDate(r[3]), testDate,
                rowCompany: curCo, rowLocation: curLoc, province: curProv,
                wearHpd: r[5], hpdType: r[6], testType: r[7], category: r[8],
                left_500: num(r[9]), left_1k: num(r[10]), left_2k: num(r[11]), left_3k: num(r[12]), left_4k: num(r[13]), left_6k: num(r[14]), left_8k: num(r[15]),
                right_500: num(r[16]), right_1k: num(r[17]), right_2k: num(r[18]), right_3k: num(r[19]), right_4k: num(r[20]), right_6k: num(r[21]), right_8k: num(r[22])
            });
        }
    }
  }
  return allRows;
}

// Helper Utils (Standardized)
function parseDate(raw) {
    if (!raw) return null;
    let s = String(raw).trim().toUpperCase();
    const MONTHS = {JAN:'01',FEB:'02',MAR:'03',APR:'04',MAY:'05',JUN:'06',JUL:'07',AUG:'08',SEP:'09',OCT:'10',NOV:'11',DEC:'12',SEPT:'09',JULY:'07',JUNE:'06'};
    const spaceMatch = s.match(/^([A-Z]+)\s+(\d{1,2})\s+(\d{4})$/);
    if (spaceMatch) return `${spaceMatch[3]}-${MONTHS[spaceMatch[1]]}-${spaceMatch[2].padStart(2,'0')}`;
    const slashMatch = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (slashMatch) return `${slashMatch[3]}-${slashMatch[1].padStart(2,'0')}-${slashMatch[2].padStart(2,'0')}`;
    return /^\d{4}-\d{2}-\d{2}$/.test(s) ? s : null;
}
function num(v) { const n = Number(String(v).replace(/[^0-9.-]/g, '')); return isNaN(n) ? null : n; }
function esc(s) { return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }