import { query, transaction } from '../db/sqlite.js'

export function renderDataTools(container, state, navigate) {
  // 1. Fetch all locations with their company names for the dropdowns
  const locations = query(`
    SELECT l.location_id, l.name as loc_name, c.name as co_name 
    FROM locations l 
    JOIN companies c ON l.company_id = c.company_id 
    WHERE l.active = 1
    ORDER BY c.name, l.name
  `);

  container.innerHTML = `
    <div class="page">
      <div class="page-header">
        <h1>Data Management Tools</h1>
      </div>

      <!-- SECTION 1: BULK MOVE EMPLOYEES -->
      <div class="form-card" style="max-width: 700px; margin-bottom: 20px;">
        <div style="margin-bottom: 25px; padding-bottom: 15px; border-bottom: 1px solid #eee;">
            <h3 style="color: var(--navy-mid); margin-bottom: 8px;">Bulk Move Employees</h3>
            <p style="font-size: 13px; color: #666;">
                Move all employees and their entire history from one location to another.
            </p>
        </div>

        <div class="form-grid">
          <div class="form-group span-2">
            <label style="font-weight: 600;">Source Location (Move FROM)</label>
            <select id="move-from" class="search-input">
              <option value="">-- Select Source --</option>
              ${locations.map(l => `<option value="${l.location_id}">${l.co_name.toUpperCase()} > ${l.loc_name}</option>`).join('')}
            </select>
          </div>

          <div class="form-group span-2">
            <label style="font-weight: 600;">Destination Location (Move TO)</label>
            <select id="move-to" class="search-input">
              <option value="">-- Select Destination --</option>
              ${locations.map(l => `<option value="${l.location_id}">${l.co_name.toUpperCase()} > ${l.loc_name}</option>`).join('')}
            </select>
          </div>
        </div>

        <div style="margin-top: 20px; text-align: right;">
          <button class="btn btn-primary" id="btn-execute-move" style="background: #d9534f; border-color: #d43f3a;">
            Execute Bulk Move
          </button>
        </div>
      </div>

      <!-- SECTION 2: LEGACY DATA IMPORT -->
      <div class="form-card" style="max-width: 700px;">
        <div style="margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #eee;">
            <h3 style="color: var(--navy-mid); margin-bottom: 8px;">Legacy Data</h3>
            <p style="font-size: 13px; color: #666;">
                Import historical records from standardized CSV files generated by the Surgical Macro.
            </p>
        </div>
        <button class="btn btn-outline" id="btn-launch-legacy" style="display: flex; align-items: center; gap: 10px;">
            <span>📥</span> Launch Legacy Importer
        </button>
      </div>
    </div>
  `;

  // --- Handlers ---

  // Handle Legacy Importer Navigation
  container.querySelector('#btn-launch-legacy').onclick = () => {
    navigate('legacy-import');
  };

  // Handle Bulk Move Logic
  container.querySelector('#btn-execute-move').onclick = () => {
    const fromId = container.querySelector('#move-from').value;
    const toId = container.querySelector('#move-to').value;

    if (!fromId || !toId || fromId === toId) {
      alert("Please select two different locations.");
      return;
    }

    const count = query(`SELECT COUNT(*) as n FROM employees WHERE location_id = ?`, [fromId])[0].n;

    if (confirm(`Move ${count} employees and all history permanently?`)) {
      try {
        transaction(({ run }) => {
          run("UPDATE employees SET location_id = ? WHERE location_id = ?", [toId, fromId]);
          run("UPDATE tests SET location_id = ? WHERE location_id = ?", [toId, fromId]);
          run("UPDATE baselines SET location_id = ? WHERE location_id = ?", [toId, fromId]);
          run("UPDATE employment SET location_id = ? WHERE location_id = ?", [toId, fromId]);
        });
        alert("Move complete!");
        navigate('dashboard');
      } catch (err) {
        alert("Error: " + err.message);
      }
    }
  };
}