import { query, run, queryOne } from '../db/sqlite.js'
import { exportDB }             from '../db/sqlite.js'
import { pickSyncFolder, getSyncFolder } from '@shared/fs/sync-folder.js'
import { isDemoLoaded, clearDemoData }   from '../db/demo.js'
import { applyTheme, saveThemeColor, loadThemeColor, DEFAULT_COLOR } from '../theme.js'

export function renderSettings(container, state, navigate) {
  const provinces = query('SELECT * FROM provinces ORDER BY province_code')

  // Load org profile from settings table
  const orgName    = queryOne(`SELECT value FROM settings WHERE key = 'org_name'`)?.value    ?? ''
  const orgAddress = queryOne(`SELECT value FROM settings WHERE key = 'org_address'`)?.value ?? ''
  const orgCity    = queryOne(`SELECT value FROM settings WHERE key = 'org_city'`)?.value    ?? ''
  const orgProvince= queryOne(`SELECT value FROM settings WHERE key = 'org_province'`)?.value ?? ''
  const orgPostal  = queryOne(`SELECT value FROM settings WHERE key = 'org_postal'`)?.value  ?? ''
  const orgPhone   = queryOne(`SELECT value FROM settings WHERE key = 'org_phone'`)?.value   ?? ''
  const orgEmail   = queryOne(`SELECT value FROM settings WHERE key = 'org_email'`)?.value   ?? ''
  const orgWebsite = queryOne(`SELECT value FROM settings WHERE key = 'org_website'`)?.value ?? ''

  container.innerHTML = `
    <div class="page">
      <div class="page-header"><h1>Settings</h1></div>

      <div class="settings-sections">

        <!-- Organization Profile -->
        <section class="settings-section">
          <h2>Organization Profile</h2>
          <p class="section-desc">
            Your organization's name and contact information. This appears on referral forms,
            reports, and other printed documents generated by MasterDB and TechTool.
          </p>
          <div class="form-grid" style="display:grid;grid-template-columns:1fr 1fr;gap:10px 16px;margin-top:8px">
            <div class="form-group" style="grid-column:1/-1">
              <label>Organization Name</label>
              <input id="org-name" type="text" value="${esc(orgName)}" placeholder="e.g. Connect Hearing Canada" />
            </div>
            <div class="form-group" style="grid-column:1/-1">
              <label>Street Address</label>
              <input id="org-address" type="text" value="${esc(orgAddress)}" placeholder="123 Main Street" />
            </div>
            <div class="form-group">
              <label>City</label>
              <input id="org-city" type="text" value="${esc(orgCity)}" placeholder="Calgary" />
            </div>
            <div class="form-group" style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
              <div>
                <label>Province</label>
                <input id="org-province" type="text" value="${esc(orgProvince)}" placeholder="AB" maxlength="2" style="text-transform:uppercase;width:70px" />
              </div>
              <div>
                <label>Postal Code</label>
                <input id="org-postal" type="text" value="${esc(orgPostal)}" placeholder="T2P 1J9" style="width:110px" />
              </div>
            </div>
            <div class="form-group">
              <label>Phone</label>
              <input id="org-phone" type="tel" value="${esc(orgPhone)}" placeholder="1-800-555-0100" />
            </div>
            <div class="form-group">
              <label>Email</label>
              <input id="org-email" type="email" value="${esc(orgEmail)}" placeholder="info@example.com" />
            </div>
            <div class="form-group" style="grid-column:1/-1">
              <label>Website</label>
              <input id="org-website" type="url" value="${esc(orgWebsite)}" placeholder="https://www.example.com" />
            </div>
          </div>
          <button class="btn btn-primary btn-sm" id="btn-save-org" style="margin-top:12px">Save Organization Profile</button>
          <div id="org-msg" class="alert hidden" style="margin-top:8px"></div>
        </section>

        <!-- Company Logo -->
        <section class="settings-section">
          <h2>Company Logo</h2>
          <p class="section-desc">Displayed at the top of the sidebar and on printed forms and reports. PNG or SVG recommended.</p>
          ${state.logoUrl ? `
            <div class="logo-preview">
              <img src="${state.logoUrl}" alt="Company logo" style="max-height: 100px; margin-bottom: 10px;" />
            </div>
            <div style="display:flex;gap:8px;margin-top:12px;align-items:center">
              <label class="btn btn-outline btn-sm logo-upload-label">
                Change Logo
                <input type="file" accept="image/*" id="logo-input" style="display:none" />
              </label>
              <button class="btn btn-ghost btn-sm" id="btn-remove-logo" style="color:var(--red)">Remove</button>
            </div>
          ` : `
            <label class="btn btn-outline btn-sm logo-upload-label">
              Upload Logo
              <input type="file" accept="image/*" id="logo-input" style="display:none" />
            </label>
          `}
          <div id="logo-msg" class="alert hidden" style="margin-top:8px"></div>
        </section>

        <!-- Theme Color -->
        <section class="settings-section">
          <h2>Theme Color</h2>
          <p class="section-desc">Brand color used for the sidebar and button highlights.</p>
          <div style="display:flex;align-items:center;gap:12px;margin-top:4px">
            <input type="color" id="theme-color-input" value="${loadThemeColor()}"
              style="width:48px;height:36px;border:1px solid var(--border);border-radius:var(--radius);cursor:pointer;padding:2px" />
            <span id="theme-color-hex" style="font-family:monospace;font-size:14px">${loadThemeColor()}</span>
            <button class="btn btn-ghost btn-sm" id="btn-reset-color">Reset to default</button>
          </div>
          <div id="theme-msg" class="alert hidden" style="margin-top:8px"></div>
        </section>

        <!-- Sync Folder -->
        <section class="settings-section">
          <h2>OneDrive Sync Folder</h2>
          <p class="section-desc">
            Connect the shared folder used to exchange data with field technicians.
          </p>
          <div class="folder-status-row">
            <span id="folder-status-label" class="${state.syncFolder ? 'status-online' : 'status-offline'}">
              ${state.syncFolder ? '● Sync folder connected' : '○ No sync folder selected'}
            </span>
          </div>
          <div style="display:flex;gap:8px;margin-top:10px">
            <button class="btn btn-primary btn-sm" id="btn-pick-folder">
              ${state.syncFolder ? 'Change Sync Folder' : 'Select Sync Folder'}
            </button>
            ${state.syncFolder ? `
              <button class="btn btn-outline btn-sm" id="btn-reauth-folder">
                Re-authorize Access
              </button>
            ` : ''}
          </div>
          <div id="folder-msg" class="alert hidden" style="margin-top:8px"></div>
        </section>

        <!-- Province rules -->
        <section class="settings-section">
          <h2>Province Rules</h2>
          <p class="section-desc">Read-only reference of classification rules and templates.</p>
          <table class="data-table">
            <thead><tr><th>Province</th><th>Regulation</th><th>Rules</th><th></th></tr></thead>
            <tbody>
              ${provinces.map(p => {
                const ruleCount = query('SELECT COUNT(*) AS n FROM classification_rules WHERE province_code = ?', [p.province_code])[0]?.n ?? 0
                return `<tr>
                  <td><strong>${esc(p.province_code)}</strong> — ${esc(p.province_name)}</td>
                  <td class="td-muted">${esc(p.regulation_ref ?? '—')}</td>
                  <td>${ruleCount}</td>
                  <td><button class="btn btn-link btn-sm btn-view-rules" data-province="${esc(p.province_code)}">View Rules →</button></td>
                </tr>`
              }).join('')}
            </tbody>
          </table>
        </section>

        <!-- Database -->
        <section class="settings-section">
          <h2>Maintenance & Backup</h2>
          <p class="section-desc">Export a copy of the internal database or clear demo data.</p>
          <div style="display:flex; gap:10px;">
            <button class="btn btn-outline btn-sm" id="btn-export-db">Export Backup (.sqlite)</button>
            ${isDemoLoaded() ? `
              <button class="btn btn-outline btn-sm" id="btn-clear-demo" style="color:var(--red);border-color:var(--red)">
                Clear Demo Data
              </button>
            ` : ''}
          </div>
        </section>

      </div>
    </div>
  `

  // --- Handlers ---

  container.querySelector('#btn-save-org').addEventListener('click', () => {
    const fields = {
      org_name:     container.querySelector('#org-name').value.trim(),
      org_address:  container.querySelector('#org-address').value.trim(),
      org_city:     container.querySelector('#org-city').value.trim(),
      org_province: container.querySelector('#org-province').value.trim().toUpperCase(),
      org_postal:   container.querySelector('#org-postal').value.trim(),
      org_phone:    container.querySelector('#org-phone').value.trim(),
      org_email:    container.querySelector('#org-email').value.trim(),
      org_website:  container.querySelector('#org-website').value.trim()
    }
    const msg = container.querySelector('#org-msg')
    if (!fields.org_name) {
      msg.className = 'alert alert-error'; msg.textContent = 'Name required.'; msg.classList.remove('hidden'); return
    }
    for (const [key, value] of Object.entries(fields)) {
      run(`INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)`, [key, value])
    }
    state.orgProfile = fields
    msg.className = 'alert alert-success'; msg.textContent = '✓ Saved.'; msg.classList.remove('hidden')
    setTimeout(() => msg.classList.add('hidden'), 2000)
  })

  container.querySelector('#logo-input')?.addEventListener('change', async e => {
    const file = e.target.files[0]; if (!file) return
    const msg = container.querySelector('#logo-msg')
    try {
      const dataUrl = await resizeImage(file, 400, 160)
      run(`INSERT OR REPLACE INTO settings (key, value) VALUES ('company_logo', ?)`, [dataUrl])
      state.logoUrl = dataUrl
      setTimeout(() => navigate('settings'), 1000)
    } catch (err) { alert(err.message) }
  })

  container.querySelector('#btn-remove-logo')?.addEventListener('click', () => {
    if (confirm('Remove logo?')) {
      run(`DELETE FROM settings WHERE key = 'company_logo'`)
      state.logoUrl = null; navigate('settings')
    }
  })

  const colorInput = container.querySelector('#theme-color-input')
  colorInput.addEventListener('input', () => {
    applyTheme(colorInput.value)
    container.querySelector('#theme-color-hex').textContent = colorInput.value
  })
  colorInput.addEventListener('change', () => saveThemeColor(colorInput.value))

  container.querySelector('#btn-reset-color').onclick = () => {
    applyTheme(DEFAULT_COLOR); saveThemeColor(DEFAULT_COLOR); navigate('settings')
  }

  container.querySelector('#btn-pick-folder').onclick = async () => {
    try {
      state.syncFolder = await pickSyncFolder(); navigate('settings')
    } catch (e) { console.error(e) }
  }

  container.querySelector('#btn-reauth-folder')?.addEventListener('click', async () => {
    try {
      state.syncFolder = await getSyncFolder(); navigate('settings')
    } catch (e) { alert(e.message) }
  })

  container.querySelectorAll('.btn-view-rules').forEach(btn => {
    btn.onclick = () => navigate('province-rules', { params: { province: btn.dataset.province } })
  })

  container.querySelector('#btn-clear-demo')?.addEventListener('click', () => {
    if (confirm('Remove demo data?')) { clearDemoData(); navigate('settings') }
  })

  container.querySelector('#btn-export-db').onclick = () => exportDB()
}

// --- Image Resize Utility ---
function resizeImage(file, maxW, maxH) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = e => {
      const img = new Image()
      img.onload = () => {
        const scale = Math.min(maxW / img.width, maxH / img.height, 1)
        const canvas = document.createElement('canvas')
        canvas.width = Math.round(img.width * scale); canvas.height = Math.round(img.height * scale)
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height)
        resolve(canvas.toDataURL('image/png'))
      }
      img.src = e.target.result
    }
    reader.readAsDataURL(file)
  })
}

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}